version: "3.9"
services:
  ganache:
    build: ./ganache
  truffle:
    build: ./truffle
    ports:
      - "8080:8080"
    depends_on:
      - "ganache"
    volumes:
      - ./code:/code
    command: ["tail", "-f", "/dev/null"]
