version: "3.9"
services:
  ganache:
    build: ./ganache
  truffle:
    build: ./truffle
    depends_on:
      - "ganache"
    volumes:
      - ./code:/code
    # command: ["tail", "-f", "/dev/null"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: bash
  